### ISSUE TITLE
Forward slashes from URLs incorrectly parsed as single line comments

### ISSUE THREAD

**Issue by redonkulus** [marko-js/htmljs-parser#70]
My previously working marko template is now failing to compile due to URL forward slashes causing `htmljs-parser` to think they are single line code comments. I believe the recently merged PR, caused this issue: https://github.com/marko-js/htmljs-parser/pull/69/files 
 
Example code:
```
let noScriptImgUrl = `https://sb.scorecardresearch.com`;
```

Marko compile error:
```
- Failed to compile "src/components/foo.marko". Error: Error: An error occurred while trying to compile template at path "/Users/Dev/app/src/components/foo.marko". Error(s) in template:
1) [src/components/foo.marko:1:1] EOF reached while parsing scriptet

    at handleErrors (/Users/Dev/app/node_modules/marko/src/compiler/Compiler.js:95:21)
    at Compiler.compile (/Users/Dev/app/node_modules/marko/src/compiler/Compiler.js:178:9)
    at _compile (/Users/Dev/app/node_modules/marko/src/compiler/index.js:88:33)
    at /Users/Dev/app/node_modules/marko/src/compiler/index.js:146:13
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

Dependencies:
- marko@4.18.0
- htmljs-parser@2.6.7

**Comment by redonkulus** [comment]
Downgrading to htmljs-parser@2.6.5 fixes the issue
